# Dependencies
markdown:         redcarpet
highlighter:      pygments
plugins:
  - jekyll-gist
  - jekyll-paginate

# Permalinks
permalink:        pretty

# Setup
title:            'Javier Lopez&#8209;Gomez'
tagline:          'personal page'
description:      'personal page'
url:              https://jalopezg-git.github.io
baseurl:          '/'

author:
  name:           'Javier Lopez-Gomez'
  url:            https://jalopezg-git.github.io/

paginate:         5

# Custom vars
github:
  repo:           https://github.com/jalopezg-git/
